const SET_BOOKS = 'SET_BOOKS';
const LOAD_BOOKS = 'LOAD_BOOKS';
const LOAD_SELECTED_BOOK = 'LOAD_SELECTED_BOOK';
const SET_SELECTED_BOOK = 'SET_SELECTED_BOOK';
const SET_BOOKS_LIMIT = 'SET_BOOKS_LIMIT'
const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
const SET_CURRENT_BOOK = 'SET_CURRENT_BOOK';
const SET_TOTAL = 'SET_TOTAL'
const ADD_TO_CART = 'ADD_TO_CART'

export {
    SET_BOOKS,
    LOAD_BOOKS,
    LOAD_SELECTED_BOOK,
    SET_SELECTED_BOOK,
    SET_BOOKS_LIMIT,
    SET_CURRENT_PAGE,
    SET_CURRENT_BOOK,
    SET_TOTAL,
    ADD_TO_CART
}